### ISSUE TITLE
Pairing with StartApp in README example?

### ISSUE THREAD

**Issue by evancz** [TheSeamau5/elm-undo-redo#4]
I don't know if this is the right choice, but it's an interesting idea.

``` elm
import Html
import Html.Events exposing (onClick)
import StartApp
import UndoList

main =
  StartApp.start { model = UndoList.fresh 0, view = view, update = UndoList.apply update }

update _ state =
  state + 1

view address (UndoList _ state _ ) = 
  Html.div 
      []
      [ Html.button 
          [ onClick address (UndoList.New ()) ]
          [ Html.text "Increment" ]
      , Html.button 
          [ onClick address UndoList.Undo ]
          [ Html.text "Undo" ]
      , Html.div 
          []
          [ Html.text (toString state) ] 
      ]
```

Now the changes are very very localized. The `StartApp.start` line gets some new stuff, and our view function gets a new button and very light modifications. Maybe this is the best way to present it in the README?

The downside is that start-app is really only for starting out at this point, so this example may not cover the common usage.

If your feeling is no, I think it's fine to close this for now and just keep it in mind as we see how important start-app becomes for beginners and if it can be made general enough that people don't really need to learn signals.

**Comment by evancz** [comment]
Oh, whoa! Continuing with this idea, there could be a function like:

``` elm
view : (Action action -> model -> Html) -> (Action action -> UndoList model -> Html)
```

So the overall change with `StartApp` would be:

``` elm
import Html
import Html.Events exposing (onClick)
import StartApp
import UndoList

main =
  StartApp.start { model = UndoList.fresh 0, view = UndoList.view view, update = UndoList.apply update }

update _ state =
  state + 1

view address state = 
  Html.div 
      []
      [ Html.button 
          [ onClick address (UndoList.New ()) ]
          [ Html.text "Increment" ]
      , Html.button 
          [ onClick address UndoList.Undo ]
          [ Html.text "Undo" ]
      , Html.div 
          []
          [ Html.text (toString state) ] 
      ]
```

Now all of the stuff is on one line, and the only changes are in the `Actions` reported back. I don't know if this is an ideal way to do things, but it certainly makes the "non-invasive" claim really really obvious.

**Comment by TheSeamau5** [comment]
You mean?

``` elm
view :  (Address (Action action) -> state -> view) 
     -> (Address (Action action) -> UndoList state -> view)
```

I'm sure I could pull this off with the `mapPresent` function. I mean, I already added foldp and mailbox as shorthands, so why not.

**Comment by evancz** [comment]
Yeah, my mistake! I think if you write the type a bit different, you can think of this as an argument that describes "how do I view the present?" and in `apply` there's an argument that says "how do I use the subaction?"

``` elm
view
  : (Address (Action action) -> model -> view) 
  -> Address (Action action)
  -> UndoList state
  -> view

update
  : (action -> model -> model)
  -> Action action
  -> UndoList model
  -> UndoList model
```

Anyway, that's a separate thing. How do you feel about using `StartApp` in the README to make it super obvious that the changes are very small?

**Comment by TheSeamau5** [comment]
I feel great about using `StartApp`. Check out the example in the PR that references this issue: https://github.com/TheSeamau5/elm-undo-redo/pull/6

I think you can use it in with `StartApp` to easily make something that supports undo/redo cuz the initial model, update, view are basically unchanged now, except for the type of the address and the actions you pass from the event handlers

**Comment by evancz** [comment]
Cool, if/when #6 happens, we can make some minor adjustments to the readme to use this. At that point, I think we have something that's very clear, easy to learn from, and can _potentially_ get on HN. They will look at github readmes sometimes if the content is cool or the title is racy :)

**Comment by TheSeamau5** [comment]
Don't worry, that PR is happening. I just called tons of stuff "update" in my code so sometimes it's calling the wrong thing. Good thing there's the typechecker and the tests to help me out.

**Comment by TheSeamau5** [comment]
`update` and `view` are now in. `apply` is gone. Feel free to make your changes

**Comment by evancz** [comment]
Sent #7 to update for this! :)

**Comment by TheSeamau5** [comment]
Ok, everything looks good. I'll just close this. Thanks a lot for your help with all of this.

**Comment by evancz** [comment]
No problem! :)
